### ISSUE TITLE
Repo is empty 😢

### ISSUE THREAD

**Issue by elielnfinic** [NdekoCode/rest-api-testing-with-mocha#1]

**Comment by NdekoCode** [comment]
I'm coding locally at the moment, tomorrow it will already be full, so you will give me recommendations and opinions, it will help me improve, I can't wait 😊!

**Comment by Cedric921** [comment]
blush blush blush

**Comment by NdekoCode** [comment]
Now you can check, all test and app is ready

**Comment by elielnfinic** [comment]
Very good
